# Eureka Server Port
server.port=6912

# Application Name
spring.application.name=eureka-server

# Eureka Server should not register itself
eureka.client.register-with-eureka=false

# Eureka Server should not fetch registry
eureka.client.fetch-registry=false
